### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'pictures/VGG19.png'

### ISSUE THREAD

**Issue by dlspm** [mc6666/MyNeuralNetwork#1]
不好意思我想請問是只有我有這個 Errror 嗎?
我Marker掉這兩行，就可以 work 了。
from keras.utils import plot_model
plot_model(model, to_file='pictures/VGG19.png')

不知道大大您這兩行用意是...?

**Comment by mc6666** [comment]
plot_model(model, to_file='pictures/VGG19.png')
是將 model structure 產出 pictures/VGG19.png，必須先建立子目錄 -- pictures
